### https://restapi-express.onrender.com <-- url de la API en produccion



### Recuperar todas los productos
GET http://localhost:3000/products


### Recuperar producto por id
GET http://localhost:3000/products/14


### Recuperar todas los productos por categoria (query params)
GET http://localhost:3000/products?category=aceites

### Crear producto con POST
POST http://localhost:3000/products
Content-Type: application/json 


{
  
    "marca": "Crema generica",
    "detalles": "100% Vegana",
    "precio": 18,
    "precioOriginal": 18,
    "categoria": "cremas",
    "imagenUrl": "./Productos/cremacannabis3.webp",
    "descripcion": "Crema 100% vegana, extraidas de cultivos argentinos de cañamo de la zona pampeana, chequear el prospecto para sus casos de uso.",
    "stock": 10
    
}

### Actualizar un producto
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
    "marca": "Pharma Serum",
    "stock": 12,
    "descripcion": "Lo actualizeeeeee"
}


### Borrar un producto 
DELETE http://localhost:3000/products/14
