### https://restapi-express.onrender.com <-- url de la API en produccion



### Recuperar todas los productos
GET http://localhost:3000/products


### Recuperar producto por id
GET http://localhost:3000/products/90bd7e1c-0bd3-11ef-9016-52660c090b1a


### Recuperar todas los productos por categoria (query params)
GET http://localhost:3000/products?category=cremas

### Crear producto con POST
POST http://localhost:3000/products
Content-Type: application/json 

{
  
    "marca": "maria marta ",
    "detalles": "raza alienigena",
    "precio": 19,
    "precioOriginal": 19,
    "categoria": "semillas",
    "imagenUrl": "./Productos/cremacannabis3.webp",
    "descripcion": "Semillas 100% ak-47. Exterior en invernadero explota",
    "stock": 32
    
}


### Actualizar un producto
PATCH http://localhost:3000/products/90bd7e1c-0bd3-11ef-9016-52660c090b1a
Content-Type: application/json

{
    "marca": "Pharma Serum",
    "stock": 12,
    "descripcion": "No lo soñeeeeeee"
}


### Borrar un producto 
DELETE http://localhost:3000/products/972b2303-0cb1-11ef-9016-52660c090b1a
